// await works only inside an async func !!!!!!


// async function test(){
//     let promise =new Promise((resolve,reject)=>{
//         setTimeout(() => {resolve("My promise worked")
            
//         }, 5000);

//     });

//     let result = await promise;

//     console.log("run after 5 second")
// }

// test()

